name: Workflow Evento
on:
  push:
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Job só executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"

  apenas-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Executando na feature
        if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
        run: echo "Execução em Feature"