name: Workflow Evento
on:
  push: 
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Job só executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"
      - name: Execução em Feature
        if: ${{ contains(github.ref, 'refs/heads/feature') }}
        run: echo "Execução em Feature"