name: Workflow Evento

on:
  push:
    branches:
      - main
      - feature

jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Job só executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"

  apenas-feature:
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    name: Execução em Feature
    runs-on: ubuntu-latest
    steps:
      - name: Executando na feature
        run: echo "Execução em Feature"